# -*- coding: utf-8 -*-
"""Problem 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t5-womG5nzTQJNmlS7GrS7xCqCv38coR
"""

import numpy as np
import pandas as pd

# ── Problem Parameters ───────────────────────────────────────────────────────
sell_price     = 650
shortage_cost  = 700   # cost to buy from competitor
beta           = 0.9
holding_cost   = 0     # set to 30 for Part (b)

# Demand distribution
demand_vals = [0, 1, 2, 3, 4, 5]
demand_prob = [0.05, 0.15, 0.22, 0.22, 0.18, 0.18]

# Ordering cost
def order_cost(j):
    if j == 0:
        return 0
    return 50 + 400 * j

# State space: inventory levels 0..MAX_INV
MAX_INV  = 10   # reasonable upper bound (max demand is 5, sensible to order up to ~10)
states   = list(range(MAX_INV + 1))

# ── Revenue function R(s, d) ─────────────────────────────────────────────────
def revenue(s, d):
    """Revenue when inventory=s and demand=d."""
    if d <= s:
        return sell_price * d
    else:
        # sell all s at $650, buy (d-s) from competitor at $700 and sell at $650
        return sell_price * s - (shortage_cost - sell_price) * (d - s)

# ── Expected revenue given starting inventory s (after order) ───────────────
def expected_revenue(s):
    return sum(demand_prob[k] * revenue(s, demand_vals[k]) for k in range(len(demand_vals)))

# ── Expected holding cost given starting inventory s ────────────────────────
def expected_holding(s):
    return sum(demand_prob[k] * max(0, s - demand_vals[k]) for k in range(len(demand_vals)))

# ── Net reward r(i, j) ───────────────────────────────────────────────────────
def net_reward(i, j, h_cost=0):
    s = i + j
    if s > MAX_INV:
        return -np.inf
    r = -order_cost(j) + expected_revenue(s) - h_cost * expected_holding(s)
    return r

# ── Transition probabilities P(i' | i, j) ────────────────────────────────────
def transition_probs(i, j):
    """Returns dict {next_state: probability}."""
    s = i + j
    probs = {}
    for k, d in enumerate(demand_vals):
        i_next = max(0, s - d)
        probs[i_next] = probs.get(i_next, 0) + demand_prob[k]
    return probs

# ── Value Iteration ───────────────────────────────────────────────────────────
def solve(h_cost=0, label="Part (a)"):
    print("=" * 70)
    print(f"  INVENTORY MDP — {label}")
    print("=" * 70)
    print(f"  beta={beta}, holding cost=${h_cost}/unit")

    tol      = 1e-6
    max_iter = 10000

    V      = {i: 0.0 for i in states}
    policy = {i: 0    for i in states}

    iteration_log = []

    for iteration in range(1, max_iter + 1):
        V_new = {}
        pol   = {}

        for i in states:
            best_val = -np.inf
            best_j   = 0

            # Try all feasible order quantities
            for j in range(0, MAX_INV - i + 1):
                r     = net_reward(i, j, h_cost)
                if r == -np.inf:
                    continue
                trans = transition_probs(i, j)
                future = sum(p * V[i_next] for i_next, p in trans.items())
                val    = r + beta * future

                if val > best_val:
                    best_val = val
                    best_j   = j

            V_new[i] = best_val
            pol[i]   = best_j

        # Convergence check
        max_diff = max(abs(V_new[i] - V[i]) for i in states)

        if iteration <= 5 or iteration % 50 == 0:
            iteration_log.append({
                "Iter"    : iteration,
                "MaxDiff" : round(max_diff, 6),
                **{f"V({i})": round(V_new[i], 2) for i in states}
            })

        V      = V_new
        policy = pol

        if max_diff < tol:
            print(f"\n  Converged after {iteration} iterations (max diff = {max_diff:.2e})\n")
            break

    # ── Iteration log ─────────────────────────────────────────────────────────
    print("  Iteration Log (selected):")
    df_log = pd.DataFrame(iteration_log)
    print(df_log.to_string(index=False))

    # ── Final value function and policy ──────────────────────────────────────
    print()
    print("=" * 70)
    print(f"  FINAL RESULTS — {label}")
    print("=" * 70)

    rows = []
    for i in states:
        j     = policy[i]
        s     = i + j
        er    = expected_revenue(s)
        eh    = expected_holding(s) * h_cost
        oc    = order_cost(j)
        r_net = net_reward(i, j, h_cost)
        trans = transition_probs(i, j)
        future = sum(p * V[i_next] for i_next, p in trans.items())

        rows.append({
            "Inv (i)"         : i,
            "Order (j*)"      : j,
            "Order-up-to (s)" : s,
            "Order Cost ($)"  : oc,
            "E[Revenue] ($)"  : round(er, 2),
            "E[Holding] ($)"  : round(eh, 2),
            "Net Reward ($)"  : round(r_net, 2),
            "V(i)"            : round(V[i], 2),
        })

    df = pd.DataFrame(rows)
    print(df.to_string(index=False))

    # ── TPM ───────────────────────────────────────────────────────────────────
    print()
    print("  Transition Probability Matrix (under optimal policy):")
    tpm = np.zeros((len(states), len(states)))
    for i in states:
        j     = policy[i]
        trans = transition_probs(i, j)
        for i_next, p in trans.items():
            tpm[i][i_next] = p

    df_tpm = pd.DataFrame(tpm,
                          index  =[f"s={i}" for i in states],
                          columns=[f"s'={i}" for i in states])
    print(df_tpm.to_string())

    # ── Policy summary ────────────────────────────────────────────────────────
    print()
    print("=" * 70)
    print(f"  OPTIMAL ORDERING POLICY SUMMARY — {label}")
    print("=" * 70)
    print(f"\n  {'Inv at end of week':>20}  {'Order qty':>10}  {'Order-up-to level':>18}")
    print(f"  {'-'*52}")
    for i in states:
        j = policy[i]
        s = i + j
        note = "  (do not order)" if j == 0 else f"  (order up to {s})"
        print(f"  {i:>20}  {j:>10}  {s:>18}{note}")

    return V, policy

# ── Part (a): No holding cost ─────────────────────────────────────────────────
V_a, pol_a = solve(h_cost=0, label="Part (a) — No Holding Cost")

# ── Part (b): With holding cost ───────────────────────────────────────────────
print()
V_b, pol_b = solve(h_cost=30, label="Part (b) — Holding Cost $30/unit")

# ── Comparison ────────────────────────────────────────────────────────────────
print()
print("=" * 70)
print("  POLICY COMPARISON: Part (a) vs Part (b)")
print("=" * 70)
print(f"\n  {'Inv (i)':>8}  {'Order* Part(a)':>15}  {'Order* Part(b)':>15}  {'Change':>10}")
print(f"  {'-'*55}")
for i in states:
    ja = pol_a[i]
    jb = pol_b[i]
    change = "fewer" if jb < ja else ("more" if jb > ja else "same")
    print(f"  {i:>8}  {ja:>15}  {jb:>15}  {change:>10}")

